### ISSUE TITLE
"make_unique" may be too difficult for beginners!

### ISSUE THREAD

**Issue by DarkSharpness** [JohnClass2023/Smart-Pointers-2023#2]
I think it's inappropriate for beginners to write modern C++ style code.
For example, `make_unique` function requires so-called "perfect forwarding" in C++, which interweaves with left/right value references. That may be too hard for beginners, I think.

```C++
// std code omitted
```

I think you should at least give some references for those beginners, and here's some of mine:

- [谈谈完美转发(Perfect Forwarding)](https://zhuanlan.zhihu.com/p/369203981)
- [Effective modern C++ 中文版(重点看 Item 23)] (https://github.com/CnTransGroup/EffectiveModernCppChinese)

**Comment by JohnClass2023** [comment]
We have covered left/right value references in our recitation class :)

**Comment by JohnClass2023** [comment]
Also, forwarding is not necessarily needed in this project.
